// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: a3abe5be22c06770f6c795ececf6b75a9bd274d40da449d747d36c7230514cc3
import * as Schema from "effect/Schema";
import type * as Contract from "./ctoxBusinessData.generated.ts";

export const NativeBusinessDataCredentialChallengeSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  connectionId: Schema.String,
  targetId: Schema.String,
  sessionEpoch: Schema.Int.check(
    Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
  ),
  nonce: Schema.optionalKey(Schema.NullOr(Schema.String)),
}) satisfies Schema.Schema<Contract.NativeBusinessDataCredentialChallenge>;

export const NativeBusinessDataDeviceProofSchema = Schema.Struct({
  publicX: Schema.String,
  publicY: Schema.String,
  signature: Schema.String,
}) satisfies Schema.Schema<Contract.NativeBusinessDataDeviceProof>;

export const NativeBusinessDataCredentialReplySchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  connectionId: Schema.String,
  sessionEpoch: Schema.Int.check(
    Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
  ),
  capabilityToken: Schema.optionalKey(Schema.NullOr(Schema.String)),
  deviceProof: Schema.optionalKey(Schema.NullOr(NativeBusinessDataDeviceProofSchema)),
}) satisfies Schema.Schema<Contract.NativeBusinessDataCredentialReply>;

export const NativeBusinessDataIdentityRequestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  challenge: Schema.String,
}) satisfies Schema.Schema<Contract.NativeBusinessDataIdentityRequest>;

export const NativeBusinessDataDeviceIdentitySchema = Schema.Struct({
  pairingId: Schema.String,
  deviceId: Schema.String,
  proofKeyThumbprint: Schema.String,
}) satisfies Schema.Schema<Contract.NativeBusinessDataDeviceIdentity>;

export const NativeBusinessDataPrincipalSchema = Schema.Struct({
  userId: Schema.String,
  authorizationEpoch: Schema.Int.check(
    Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
  ),
  device: Schema.optionalKey(Schema.NullOr(NativeBusinessDataDeviceIdentitySchema)),
}) satisfies Schema.Schema<Contract.NativeBusinessDataPrincipal>;

export const NativeBusinessDataPeerIdentitySchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  challenge: Schema.String,
  instanceId: Schema.String,
  publicIdentity: Schema.String,
  channelBinding: Schema.String,
  principal: Schema.optionalKey(Schema.NullOr(NativeBusinessDataPrincipalSchema)),
  signature: Schema.String,
}) satisfies Schema.Schema<Contract.NativeBusinessDataPeerIdentity>;

export const NativeBusinessDataSessionRefSchema = Schema.Struct({
  handle: Schema.String,
  generation: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
}) satisfies Schema.Schema<Contract.NativeBusinessDataSessionRef>;

export const NativeBusinessDataBindingSchema = Schema.Struct({
  targetId: Schema.String,
  instanceId: Schema.String,
  userId: Schema.String,
}) satisfies Schema.Schema<Contract.NativeBusinessDataBinding>;

export const NativeBusinessDataScopeSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("instance") }),
  Schema.Struct({ type: Schema.Literal("project"), projectId: Schema.String }),
  Schema.Struct({
    type: Schema.Literal("thread"),
    projectId: Schema.String,
    threadId: Schema.String,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataScope>;

export const NativeBusinessDataQuerySchema = Schema.Struct({
  collection: Schema.String,
  scope: NativeBusinessDataScopeSchema,
  query: Schema.Unknown,
  pageSize: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
}) satisfies Schema.Schema<Contract.NativeBusinessDataQuery>;

export const NativeBusinessDataRecordSchema = Schema.Struct({
  documentId: Schema.String,
  document: Schema.Unknown,
}) satisfies Schema.Schema<Contract.NativeBusinessDataRecord>;

export const NativeBusinessDataCommandSchema = Schema.Struct({
  commandId: Schema.String,
  commandType: Schema.String,
  payload: Schema.Unknown,
}) satisfies Schema.Schema<Contract.NativeBusinessDataCommand>;

export const NativeBusinessDataCommandStatusSchema = Schema.Literals([
  "pending",
  "completed",
  "failed",
  "unknown",
]) satisfies Schema.Schema<Contract.NativeBusinessDataCommandStatus>;

export const NativeBusinessDataCommandStateSchema = Schema.Struct({
  commandId: Schema.String,
  status: NativeBusinessDataCommandStatusSchema,
  result: Schema.optionalKey(Schema.NullOr(Schema.Unknown)),
  error: Schema.optionalKey(Schema.NullOr(Schema.String)),
}) satisfies Schema.Schema<Contract.NativeBusinessDataCommandState>;

export const NativeBusinessDataOperationSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("open"), targetId: Schema.String }),
  Schema.Struct({ type: Schema.Literal("status"), session: NativeBusinessDataSessionRefSchema }),
  Schema.Struct({ type: Schema.Literal("close"), session: NativeBusinessDataSessionRefSchema }),
  Schema.Struct({
    type: Schema.Literal("query"),
    session: NativeBusinessDataSessionRefSchema,
    query: NativeBusinessDataQuerySchema,
    pageCursor: Schema.optionalKey(Schema.NullOr(Schema.String)),
  }),
  Schema.Struct({
    type: Schema.Literal("watch"),
    session: NativeBusinessDataSessionRefSchema,
    query: NativeBusinessDataQuerySchema,
    resumeCursor: Schema.optionalKey(Schema.NullOr(Schema.String)),
  }),
  Schema.Struct({
    type: Schema.Literal("unwatch"),
    session: NativeBusinessDataSessionRefSchema,
    subscriptionId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("submitCommand"),
    session: NativeBusinessDataSessionRefSchema,
    command: NativeBusinessDataCommandSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("observeCommand"),
    session: NativeBusinessDataSessionRefSchema,
    commandId: Schema.String,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataOperation>;

export const NativeBusinessDataRequestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  operation: NativeBusinessDataOperationSchema,
}) satisfies Schema.Schema<Contract.NativeBusinessDataRequest>;

export const NativeBusinessDataSessionStateSchema = Schema.Union([
  Schema.Struct({
    type: Schema.Literal("resolving"),
    session: NativeBusinessDataSessionRefSchema,
    targetId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("ready"),
    session: NativeBusinessDataSessionRefSchema,
    binding: NativeBusinessDataBindingSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("disconnected"),
    session: NativeBusinessDataSessionRefSchema,
    binding: NativeBusinessDataBindingSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("revoked"),
    session: NativeBusinessDataSessionRefSchema,
    reason: Schema.String,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataSessionState>;

export const NativeBusinessDataErrorCodeSchema = Schema.Literals([
  "invalidRequest",
  "unsupported",
  "unauthorized",
  "unknownSession",
  "staleGeneration",
  "disconnected",
  "revoked",
  "schemaMismatch",
  "limitExceeded",
  "resetRequired",
  "internal",
]) satisfies Schema.Schema<Contract.NativeBusinessDataErrorCode>;

export const NativeBusinessDataResultSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("session"), state: NativeBusinessDataSessionStateSchema }),
  Schema.Struct({
    type: Schema.Literal("page"),
    session: NativeBusinessDataSessionRefSchema,
    snapshotId: Schema.String,
    records: Schema.Array(NativeBusinessDataRecordSchema),
    nextPageCursor: Schema.optionalKey(Schema.NullOr(Schema.String)),
    snapshotComplete: Schema.Boolean,
  }),
  Schema.Struct({
    type: Schema.Literal("subscribed"),
    session: NativeBusinessDataSessionRefSchema,
    subscriptionId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("command"),
    session: NativeBusinessDataSessionRefSchema,
    state: NativeBusinessDataCommandStateSchema,
  }),
  Schema.Struct({ type: Schema.Literal("closed"), session: NativeBusinessDataSessionRefSchema }),
  Schema.Struct({
    type: Schema.Literal("unwatched"),
    session: NativeBusinessDataSessionRefSchema,
    subscriptionId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("rejected"),
    code: NativeBusinessDataErrorCodeSchema,
    message: Schema.String,
    retryable: Schema.Boolean,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataResult>;

export const NativeBusinessDataResponseSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  result: NativeBusinessDataResultSchema,
}) satisfies Schema.Schema<Contract.NativeBusinessDataResponse>;

export const NativeBusinessDataEventPayloadSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("snapshotStart"), snapshotId: Schema.String }),
  Schema.Struct({
    type: Schema.Literal("snapshotPage"),
    snapshotId: Schema.String,
    records: Schema.Array(NativeBusinessDataRecordSchema),
  }),
  Schema.Struct({
    type: Schema.Literal("snapshotEnd"),
    snapshotId: Schema.String,
    cursor: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("upsert"),
    cursor: Schema.String,
    record: NativeBusinessDataRecordSchema,
    recovery: Schema.Boolean,
  }),
  Schema.Struct({
    type: Schema.Literal("remove"),
    cursor: Schema.String,
    documentId: Schema.String,
    recovery: Schema.Boolean,
  }),
  Schema.Struct({ type: Schema.Literal("caughtUp"), cursor: Schema.String }),
  Schema.Struct({ type: Schema.Literal("reset"), code: NativeBusinessDataErrorCodeSchema }),
  Schema.Struct({ type: Schema.Literal("revoked"), message: Schema.String }),
  Schema.Struct({ type: Schema.Literal("command"), state: NativeBusinessDataCommandStateSchema }),
  Schema.Struct({
    type: Schema.Literal("error"),
    code: NativeBusinessDataErrorCodeSchema,
    message: Schema.String,
    retryable: Schema.Boolean,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataEventPayload>;

export const NativeBusinessDataEventSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  session: NativeBusinessDataSessionRefSchema,
  subscriptionId: Schema.String,
  sequence: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  payload: NativeBusinessDataEventPayloadSchema,
}) satisfies Schema.Schema<Contract.NativeBusinessDataEvent>;

export const NativeBusinessDataHostFrameSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("request"), request: NativeBusinessDataRequestSchema }),
  Schema.Struct({ type: Schema.Literal("response"), response: NativeBusinessDataResponseSchema }),
  Schema.Struct({ type: Schema.Literal("event"), event: NativeBusinessDataEventSchema }),
  Schema.Struct({
    type: Schema.Literal("credentialChallenge"),
    challenge: NativeBusinessDataCredentialChallengeSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("credentialReply"),
    reply: NativeBusinessDataCredentialReplySchema,
  }),
]) satisfies Schema.Schema<Contract.NativeBusinessDataHostFrame>;
