// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: bfb3ad8fba0458085807b14edb1ea87ee1bd64990201ef3ee9f3b00e026a41c3
export const CTOX_SYNC_CONTRACT_VERSION = 1 as const;
export const CTOX_SYNC_AUTHORITY_PROTOCOL_VERSION = 5 as const;
export const CTOX_SYNC_IPC_PROTOCOL_VERSION = 1 as const;
export const CTOX_SYNC_IPC_MAX_FRAME_BYTES = 65536 as const;
export const CTOX_SYNC_IPC_DEADLINE_MILLIS = 10000 as const;

export type WorkspaceEntryKind = "file" | "symlink";

export interface ExecutionPeer {
  readonly identity: string;
  readonly executor: boolean;
  readonly dataReplica: boolean;
}

export interface SyncHostTiming {
  readonly heartbeatMs: number;
  readonly electionMinMs: number;
  readonly electionMaxMs: number;
}

export interface SyncHostConfiguration {
  readonly version: number;
  readonly scopeId: string;
  readonly local: SyncHostMember;
  readonly voters: Readonly<Record<string, ExecutionPeer>>;
  readonly timing: SyncHostTiming;
}

export interface SyncHostTransport {
  readonly signalingUrls: ReadonlyArray<string>;
  readonly iceServers: ReadonlyArray<SyncHostIceServer>;
}

export interface SyncHostIceServer {
  readonly urls: ReadonlyArray<string>;
  readonly username: string;
  readonly credential: string;
}

export interface WorkerMembership {
  readonly nodeId: number;
  readonly identity: string;
  readonly dataReplica: boolean;
  readonly revoked: boolean;
}

export interface SyncIpcRequest {
  readonly version: number;
  readonly requestId: string;
  readonly operation: SyncIpcOperation;
}

export interface SyncIpcResponse {
  readonly version: number;
  readonly requestId: string;
  readonly result: SyncIpcResult;
}

export interface ExecutionSpec {
  readonly jobId: string;
  readonly sessionId: string;
  readonly scopeId: string;
  readonly harness: string;
  readonly harnessVersion: string;
  readonly modelRouteId: string;
  readonly gatewayAccountId: string;
  readonly modelId: string;
  readonly requiredCapabilities: ReadonlyArray<string>;
}

export interface ExecutionOwnership {
  readonly nodeId: number;
  readonly generation: number;
}

export interface CheckpointCopyReceipt {
  readonly version: number;
  readonly nodeId: number;
  readonly spec: ExecutionSpec;
  readonly ownership: ExecutionOwnership;
  readonly checkpointDigest: string;
  readonly sequence: number;
  readonly signature: string;
}

export interface ArtifactRef {
  readonly sha256: string;
  readonly sizeBytes: number;
}

export interface WorkspaceEntry {
  readonly path: string;
  readonly kind: WorkspaceEntryKind;
  readonly artifact: ArtifactRef;
  readonly executable: boolean;
}

export interface SessionManifest {
  readonly version: number;
  readonly scopeId: string;
  readonly sessionId: string;
  readonly harness: string;
  readonly harnessVersion: string;
  readonly modelRouteId: string;
  readonly gatewayAccountId: string;
  readonly modelId: string;
  readonly requiredCapabilities: ReadonlyArray<string>;
  readonly credentialReferences: ReadonlyArray<string>;
}

export interface CheckpointManifest {
  readonly version: number;
  readonly session: SessionManifest;
  readonly sequence: number;
  readonly baseCommit?: string | null;
  readonly history: ReadonlyArray<ArtifactRef>;
  readonly attachments: ReadonlyArray<ArtifactRef>;
  readonly workspace: ReadonlyArray<WorkspaceEntry>;
  readonly providerState: ReadonlyArray<WorkspaceEntry>;
  readonly pendingEffects: ReadonlyArray<PendingEffect>;
}

export interface PendingEffect {
  readonly effectId: string;
  readonly idempotencyKey?: string | null;
  readonly description: string;
}

export interface AppRelease {
  readonly appId: string;
  readonly version: string;
  readonly sha256: string;
  readonly schemaHash: string;
}

export interface RuntimeManifest {
  readonly version: number;
  readonly instanceId: string;
  readonly shellVersion: string;
  readonly shellSha256: string;
  readonly syncProtocolVersion: number;
  readonly schemaHash: string;
  readonly nativeVersion: string;
  readonly apps: ReadonlyArray<AppRelease>;
}

export type SyncHostMember =
  { readonly type: "voter"; readonly nodeId: number } |
  { readonly type: "worker"; readonly member: WorkerMembership };

export type AuthorityFailure =
  { readonly type: "notLeader"; readonly leader: number | null } |
  { readonly type: "unavailable"; readonly reason: string } |
  { readonly type: "rejected"; readonly reason: string };

export type SyncIpcOperation =
  { readonly type: "hello";  } |
  { readonly type: "workerMembership"; readonly nodeId: number } |
  { readonly type: "admitWorker"; readonly worker: WorkerMembership } |
  { readonly type: "revokeWorker"; readonly nodeId: number } |
  { readonly type: "create"; readonly spec: ExecutionSpec } |
  { readonly type: "validate"; readonly jobId: string; readonly ownership: ExecutionOwnership } |
  { readonly type: "beginEffect"; readonly jobId: string; readonly ownership: ExecutionOwnership; readonly effectId: string } |
  { readonly type: "completeEffect"; readonly jobId: string; readonly ownership: ExecutionOwnership; readonly effectId: string } |
  { readonly type: "stop"; readonly jobId: string; readonly ownership: ExecutionOwnership };

export type SyncIpcResult =
  { readonly type: "workerMembership"; readonly nodeId: number; readonly worker: WorkerMembership | null } |
  { readonly type: "workerApplied"; readonly worker: WorkerMembership } |
  { readonly type: "workerReplayed"; readonly worker: WorkerMembership } |
  { readonly type: "ready"; readonly nodeId: number; readonly scopeId: string; readonly protocolVersion: number } |
  { readonly type: "authorized"; readonly spec: ExecutionSpec; readonly ownership: ExecutionOwnership } |
  { readonly type: "applied"; readonly spec: ExecutionSpec; readonly ownership: ExecutionOwnership } |
  { readonly type: "replayed"; readonly spec: ExecutionSpec; readonly ownership: ExecutionOwnership } |
  { readonly type: "rejected"; readonly reason: string } |
  { readonly type: "unavailable"; readonly reason: string };
