// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: 2ba5493d55da1100934f2aaf13b24b71df11759f33493f7e2aca725567e8182f
import * as Schema from "effect/Schema";
import type * as Contract from "./ctoxSync.generated.ts";

export const ExecutionPeerSchema = Schema.Struct({
  identity: Schema.String,
  executor: Schema.Boolean,
  dataReplica: Schema.Boolean,
}) satisfies Schema.Schema<Contract.ExecutionPeer>;

export const SyncHostTimingSchema = Schema.Struct({
  heartbeatMs: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  electionMinMs: Schema.Int.check(
    Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
  ),
  electionMaxMs: Schema.Int.check(
    Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
  ),
}) satisfies Schema.Schema<Contract.SyncHostTiming>;

export const WorkerMembershipSchema = Schema.Struct({
  nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  identity: Schema.String,
  dataReplica: Schema.Boolean,
  revoked: Schema.Boolean,
}) satisfies Schema.Schema<Contract.WorkerMembership>;

export const SyncHostMemberSchema = Schema.Union([
  Schema.Struct({
    type: Schema.Literal("voter"),
    nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  }),
  Schema.Struct({ type: Schema.Literal("worker"), member: WorkerMembershipSchema }),
]) satisfies Schema.Schema<Contract.SyncHostMember>;

export const SyncHostConfigurationSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  scopeId: Schema.String,
  local: SyncHostMemberSchema,
  voters: Schema.Record(Schema.String, ExecutionPeerSchema),
  timing: SyncHostTimingSchema,
}) satisfies Schema.Schema<Contract.SyncHostConfiguration>;

export const SyncHostIceServerSchema = Schema.Struct({
  urls: Schema.Array(Schema.String),
  username: Schema.String,
  credential: Schema.String,
}) satisfies Schema.Schema<Contract.SyncHostIceServer>;

export const SyncHostTransportSchema = Schema.Struct({
  signalingUrls: Schema.Array(Schema.String),
  iceServers: Schema.Array(SyncHostIceServerSchema),
}) satisfies Schema.Schema<Contract.SyncHostTransport>;

export const ExecutionSpecSchema = Schema.Struct({
  jobId: Schema.String,
  sessionId: Schema.String,
  scopeId: Schema.String,
  harness: Schema.String,
  harnessVersion: Schema.String,
  modelRouteId: Schema.String,
  gatewayAccountId: Schema.String,
  modelId: Schema.String,
  requiredCapabilities: Schema.Array(Schema.String),
}) satisfies Schema.Schema<Contract.ExecutionSpec>;

export const ExecutionOwnershipSchema = Schema.Struct({
  nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  generation: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
}) satisfies Schema.Schema<Contract.ExecutionOwnership>;

export const CheckpointCopyReceiptSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  spec: ExecutionSpecSchema,
  ownership: ExecutionOwnershipSchema,
  checkpointDigest: Schema.String,
  sequence: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  signature: Schema.String,
}) satisfies Schema.Schema<Contract.CheckpointCopyReceipt>;

export const SyncIpcOperationSchema = Schema.Union([
  Schema.Struct({ type: Schema.Literal("hello") }),
  Schema.Struct({
    type: Schema.Literal("workerMembership"),
    nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  }),
  Schema.Struct({ type: Schema.Literal("admitWorker"), worker: WorkerMembershipSchema }),
  Schema.Struct({
    type: Schema.Literal("revokeWorker"),
    nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  }),
  Schema.Struct({ type: Schema.Literal("create"), spec: ExecutionSpecSchema }),
  Schema.Struct({
    type: Schema.Literal("validate"),
    jobId: Schema.String,
    ownership: ExecutionOwnershipSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("protectCheckpoint"),
    jobId: Schema.String,
    ownership: ExecutionOwnershipSchema,
    receipts: Schema.Array(CheckpointCopyReceiptSchema),
  }),
  Schema.Struct({
    type: Schema.Literal("takeOver"),
    jobId: Schema.String,
    expected: ExecutionOwnershipSchema,
    checkpointDigest: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("beginEffect"),
    jobId: Schema.String,
    ownership: ExecutionOwnershipSchema,
    effectId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("completeEffect"),
    jobId: Schema.String,
    ownership: ExecutionOwnershipSchema,
    effectId: Schema.String,
  }),
  Schema.Struct({
    type: Schema.Literal("stop"),
    jobId: Schema.String,
    ownership: ExecutionOwnershipSchema,
  }),
]) satisfies Schema.Schema<Contract.SyncIpcOperation>;

export const SyncIpcRequestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  operation: SyncIpcOperationSchema,
}) satisfies Schema.Schema<Contract.SyncIpcRequest>;

export const SyncIpcResultSchema = Schema.Union([
  Schema.Struct({
    type: Schema.Literal("workerMembership"),
    nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
    worker: Schema.optionalKey(Schema.NullOr(WorkerMembershipSchema)),
  }),
  Schema.Struct({ type: Schema.Literal("workerApplied"), worker: WorkerMembershipSchema }),
  Schema.Struct({ type: Schema.Literal("workerReplayed"), worker: WorkerMembershipSchema }),
  Schema.Struct({
    type: Schema.Literal("ready"),
    nodeId: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
    scopeId: Schema.String,
    protocolVersion: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  }),
  Schema.Struct({
    type: Schema.Literal("authorized"),
    spec: ExecutionSpecSchema,
    ownership: ExecutionOwnershipSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("applied"),
    spec: ExecutionSpecSchema,
    ownership: ExecutionOwnershipSchema,
  }),
  Schema.Struct({
    type: Schema.Literal("replayed"),
    spec: ExecutionSpecSchema,
    ownership: ExecutionOwnershipSchema,
  }),
  Schema.Struct({ type: Schema.Literal("rejected"), reason: Schema.String }),
  Schema.Struct({ type: Schema.Literal("unavailable"), reason: Schema.String }),
]) satisfies Schema.Schema<Contract.SyncIpcResult>;

export const SyncIpcResponseSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  requestId: Schema.String,
  result: SyncIpcResultSchema,
}) satisfies Schema.Schema<Contract.SyncIpcResponse>;

export const ArtifactRefSchema = Schema.Struct({
  sha256: Schema.String,
  sizeBytes: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
}) satisfies Schema.Schema<Contract.ArtifactRef>;

export const WorkspaceEntryKindSchema = Schema.Literals([
  "file",
  "symlink",
]) satisfies Schema.Schema<Contract.WorkspaceEntryKind>;

export const WorkspaceEntrySchema = Schema.Struct({
  path: Schema.String,
  kind: WorkspaceEntryKindSchema,
  artifact: ArtifactRefSchema,
  executable: Schema.Boolean,
}) satisfies Schema.Schema<Contract.WorkspaceEntry>;

export const SessionManifestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  scopeId: Schema.String,
  sessionId: Schema.String,
  harness: Schema.String,
  harnessVersion: Schema.String,
  modelRouteId: Schema.String,
  gatewayAccountId: Schema.String,
  modelId: Schema.String,
  requiredCapabilities: Schema.Array(Schema.String),
  credentialReferences: Schema.Array(Schema.String),
}) satisfies Schema.Schema<Contract.SessionManifest>;

export const GitWorkspaceStateSchema = Schema.Struct({
  baseCommit: Schema.String,
  indexPatch: ArtifactRefSchema,
  worktreePatch: ArtifactRefSchema,
  requiredUntracked: Schema.Array(WorkspaceEntrySchema),
  deletedPaths: Schema.Array(Schema.String),
}) satisfies Schema.Schema<Contract.GitWorkspaceState>;

export const PendingEffectSchema = Schema.Struct({
  effectId: Schema.String,
  idempotencyKey: Schema.optionalKey(Schema.NullOr(Schema.String)),
  description: Schema.String,
}) satisfies Schema.Schema<Contract.PendingEffect>;

export const CheckpointManifestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  session: SessionManifestSchema,
  sequence: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
  workspaceState: GitWorkspaceStateSchema,
  history: Schema.Array(ArtifactRefSchema),
  attachments: Schema.Array(ArtifactRefSchema),
  workspace: Schema.Array(WorkspaceEntrySchema),
  providerState: Schema.Array(WorkspaceEntrySchema),
  pendingEffects: Schema.Array(PendingEffectSchema),
}) satisfies Schema.Schema<Contract.CheckpointManifest>;

export const AppReleaseSchema = Schema.Struct({
  appId: Schema.String,
  version: Schema.String,
  sha256: Schema.String,
  schemaHash: Schema.String,
}) satisfies Schema.Schema<Contract.AppRelease>;

export const RuntimeManifestSchema = Schema.Struct({
  version: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  instanceId: Schema.String,
  shellVersion: Schema.String,
  shellSha256: Schema.String,
  syncProtocolVersion: Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: 4294967295 })),
  schemaHash: Schema.String,
  nativeVersion: Schema.String,
  apps: Schema.Array(AppReleaseSchema),
}) satisfies Schema.Schema<Contract.RuntimeManifest>;

export const AuthorityFailureSchema = Schema.Union([
  Schema.Struct({
    type: Schema.Literal("notLeader"),
    leader: Schema.optionalKey(
      Schema.NullOr(
        Schema.Int.check(Schema.isBetween({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER })),
      ),
    ),
  }),
  Schema.Struct({ type: Schema.Literal("unavailable"), reason: Schema.String }),
  Schema.Struct({ type: Schema.Literal("rejected"), reason: Schema.String }),
]) satisfies Schema.Schema<Contract.AuthorityFailure>;
