// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: 1d9a7f2531cc70d942a9c3763f0d47076a9c732ff2712f84bdcfcf94d429e249
export const CTOX_BUSINESS_DATA_CONTRACT_VERSION = 1 as const;
export const CTOX_BUSINESS_DATA_PROTOCOL_VERSION = 1 as const;
export const CTOX_BUSINESS_DATA_MAX_PAGE_DOCUMENTS = 200 as const;
export const CTOX_BUSINESS_DATA_MAX_SNAPSHOT_BYTES = 2097152 as const;

export type NativeBusinessDataCommandStatus = "pending" | "completed" | "failed" | "unknown";

export type NativeBusinessDataErrorCode =
  | "invalidRequest"
  | "unsupported"
  | "unauthorized"
  | "unknownSession"
  | "staleGeneration"
  | "disconnected"
  | "revoked"
  | "schemaMismatch"
  | "limitExceeded"
  | "resetRequired"
  | "internal";

export interface NativeBusinessDataSessionRef {
  readonly handle: string;
  readonly generation: number;
}

export interface NativeBusinessDataBinding {
  readonly targetId: string;
  readonly instanceId: string;
  readonly userId: string;
}

export interface NativeBusinessDataQuery {
  readonly collection: string;
  readonly scope: NativeBusinessDataScope;
  readonly query: unknown;
  readonly pageSize: number;
}

export interface NativeBusinessDataRecord {
  readonly documentId: string;
  readonly document: unknown;
}

export interface NativeBusinessDataCommand {
  readonly commandId: string;
  readonly commandType: string;
  readonly payload: unknown;
}

export interface NativeBusinessDataCommandState {
  readonly commandId: string;
  readonly status: NativeBusinessDataCommandStatus;
  readonly result?: unknown | null;
  readonly error?: string | null;
}

export interface NativeBusinessDataRequest {
  readonly version: number;
  readonly requestId: string;
  readonly operation: NativeBusinessDataOperation;
}

export interface NativeBusinessDataResponse {
  readonly version: number;
  readonly requestId: string;
  readonly result: NativeBusinessDataResult;
}

export interface NativeBusinessDataEvent {
  readonly version: number;
  readonly session: NativeBusinessDataSessionRef;
  readonly subscriptionId: string;
  readonly sequence: number;
  readonly payload: NativeBusinessDataEventPayload;
}

export type NativeBusinessDataScope =
  | { readonly type: "instance" }
  | { readonly type: "project"; readonly projectId: string }
  | { readonly type: "thread"; readonly projectId: string; readonly threadId: string };

export type NativeBusinessDataSessionState =
  | {
      readonly type: "resolving";
      readonly session: NativeBusinessDataSessionRef;
      readonly targetId: string;
    }
  | {
      readonly type: "ready";
      readonly session: NativeBusinessDataSessionRef;
      readonly binding: NativeBusinessDataBinding;
    }
  | {
      readonly type: "disconnected";
      readonly session: NativeBusinessDataSessionRef;
      readonly binding: NativeBusinessDataBinding;
    }
  | {
      readonly type: "revoked";
      readonly session: NativeBusinessDataSessionRef;
      readonly reason: string;
    };

export type NativeBusinessDataOperation =
  | { readonly type: "open"; readonly targetId: string }
  | { readonly type: "status"; readonly session: NativeBusinessDataSessionRef }
  | { readonly type: "close"; readonly session: NativeBusinessDataSessionRef }
  | {
      readonly type: "query";
      readonly session: NativeBusinessDataSessionRef;
      readonly query: NativeBusinessDataQuery;
      readonly pageCursor?: string | null;
    }
  | {
      readonly type: "watch";
      readonly session: NativeBusinessDataSessionRef;
      readonly query: NativeBusinessDataQuery;
      readonly resumeCursor?: string | null;
    }
  | {
      readonly type: "unwatch";
      readonly session: NativeBusinessDataSessionRef;
      readonly subscriptionId: string;
    }
  | {
      readonly type: "submitCommand";
      readonly session: NativeBusinessDataSessionRef;
      readonly command: NativeBusinessDataCommand;
    }
  | {
      readonly type: "observeCommand";
      readonly session: NativeBusinessDataSessionRef;
      readonly commandId: string;
    };

export type NativeBusinessDataResult =
  | { readonly type: "session"; readonly state: NativeBusinessDataSessionState }
  | {
      readonly type: "page";
      readonly session: NativeBusinessDataSessionRef;
      readonly snapshotId: string;
      readonly records: ReadonlyArray<NativeBusinessDataRecord>;
      readonly nextPageCursor?: string | null;
      readonly snapshotComplete: boolean;
    }
  | {
      readonly type: "subscribed";
      readonly session: NativeBusinessDataSessionRef;
      readonly subscriptionId: string;
    }
  | {
      readonly type: "command";
      readonly session: NativeBusinessDataSessionRef;
      readonly state: NativeBusinessDataCommandState;
    }
  | { readonly type: "closed"; readonly session: NativeBusinessDataSessionRef }
  | {
      readonly type: "unwatched";
      readonly session: NativeBusinessDataSessionRef;
      readonly subscriptionId: string;
    }
  | {
      readonly type: "rejected";
      readonly code: NativeBusinessDataErrorCode;
      readonly message: string;
      readonly retryable: boolean;
    };

export type NativeBusinessDataEventPayload =
  | { readonly type: "snapshotStart"; readonly snapshotId: string }
  | {
      readonly type: "snapshotPage";
      readonly snapshotId: string;
      readonly records: ReadonlyArray<NativeBusinessDataRecord>;
    }
  | { readonly type: "snapshotEnd"; readonly snapshotId: string; readonly cursor: string }
  | {
      readonly type: "upsert";
      readonly cursor: string;
      readonly record: NativeBusinessDataRecord;
      readonly recovery: boolean;
    }
  | {
      readonly type: "remove";
      readonly cursor: string;
      readonly documentId: string;
      readonly recovery: boolean;
    }
  | { readonly type: "caughtUp"; readonly cursor: string }
  | { readonly type: "reset"; readonly code: NativeBusinessDataErrorCode }
  | { readonly type: "revoked"; readonly message: string }
  | { readonly type: "command"; readonly state: NativeBusinessDataCommandState }
  | {
      readonly type: "error";
      readonly code: NativeBusinessDataErrorCode;
      readonly message: string;
      readonly retryable: boolean;
    };
