// SPDX-License-Identifier: AGPL-3.0-only
// Consumer of CTOX 79b0a2428's workjet-supervisor-route-computation-v2.json.
// Native Rust and browser validators are generated by CTOX from that fixture.
import * as Schema from "effect/Schema";
import { ConfiguredSupervisorRoute } from "./workjetSupervisorRoute.generated.ts";

const text = (maximum: number, minimum = 1) =>
  Schema.String.check(
    Schema.makeFilter((value) => {
      const length = Array.from(value).length;
      return length >= minimum && length <= maximum;
    }),
  );
const integer = (minimum: number) =>
  Schema.Int.check(Schema.isBetween({ minimum, maximum: Number.MAX_SAFE_INTEGER }));

export const SupervisorRouteCapabilitiesV2 = Schema.Struct({
  schema: Schema.Literal("ctox.workjet.supervisor.route-capabilities.v2"),
  project_id: text(256),
  supervisor_thread_id: text(256),
  read_schema: Schema.Literal("ctox.workjet.supervisor.route-display.v2"),
  read_command: Schema.Literal("ctox.workjet.project.supervisor.route.read.v2"),
});

export const ActualSupervisorComputationV2 = Schema.Struct({
  receipt_id: text(64, 64),
  execution_key: text(256),
  selected_route: Schema.Struct({
    luma_id: text(160),
    configuration_revision: integer(1),
    route_id: text(160),
  }),
  harness: text(32),
  computer_id: text(256),
  account_id: text(256),
  model: text(256),
  model_operation_id: text(256),
  native_message_id: text(256),
  upstream_request_id: text(256),
  sdk_session_id: text(256),
  sdk_turn_id: text(256),
  sdk_assistant_id: text(256),
  sdk_result_id: text(256),
  model_finished_at_ms: integer(0),
  published_at_ms: integer(0),
});
export type ActualSupervisorComputationV2 = typeof ActualSupervisorComputationV2.Type;

export const SupervisorRouteDisplayV2 = Schema.Struct({
  schema: Schema.Literal("ctox.workjet.supervisor.route-display.v2"),
  project_id: text(128),
  supervisor_thread_id: text(36),
  configured: Schema.optionalKey(Schema.NullOr(ConfiguredSupervisorRoute)),
  actual: Schema.optionalKey(Schema.NullOr(ActualSupervisorComputationV2)),
});
export type SupervisorRouteDisplayV2 = typeof SupervisorRouteDisplayV2.Type;
