// SPDX-License-Identifier: MIT OR AGPL-3.0-only
// @effect-diagnostics nodeBuiltinImport:off - Resolving and digesting an on-disk executable is an explicit Electron filesystem boundary.
import * as NodeCrypto from "node:crypto";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";

import hostReleasePin from "../../resources/provider-gateway/host-release.pin.json" with { type: "json" };
import * as DesktopEnvironment from "../app/DesktopEnvironment.ts";

/**
 * Decides which `workjet-provider-gateway-host` executable a Workjet desktop
 * process should run.
 *
 * There are exactly three sources, and which one applies is decided here rather
 * than anywhere else:
 *
 *   - PINNED   — a `provider-gateway-host-v*` release artifact whose bytes
 *                reproduce the SHA-256 recorded in
 *                `resources/provider-gateway/host-release.pin.json`. This is
 *                the only source a PACKAGED build ever accepts.
 *   - WORKSPACE — the current repository release build under
 *                 `native/provider-gateway-workjet-host/target/release`. A
 *                 development desktop prefers this over a state-directory
 *                 copy so a stale host cannot drift behind the server's
 *                 readiness protocol.
 *   - LOCAL     — the final development fallback: whatever the server's existing
 *                default resolution finds (the
 *                `WORKJET_PROVIDER_GATEWAY_HOST_EXECUTABLE` override, else
 *                `<stateDir>/provider-gateway-host`), i.e. a locally built
 *                `cargo build --release` binary a developer placed there.
 *
 * Rules:
 *   1. An explicit `WORKJET_PROVIDER_GATEWAY_HOST_EXECUTABLE` always wins; a
 *      developer pointing at a specific build is never second-guessed.
 *   2. Packaged + unmet pin (unreleased, unsupported platform, missing file, or
 *      digest mismatch) is a hard, named failure. A packaged app has no
 *      toolchain, so silently falling back would only produce a confusing
 *      "gateway won't start" later.
 *   3. Development + unmet pin falls back to LOCAL and says why.
 *
 * The pin file is generated by
 * `node scripts/provider-gateway-host-artifacts.ts pin`; its schema and the
 * artifact naming contract live in `scripts/lib/provider-gateway-host-artifacts.ts`.
 */

export const PROVIDER_GATEWAY_HOST_PIN_SCHEMA = "workjet.provider-gateway-host.pin.v1";
export const PROVIDER_GATEWAY_HOST_COMPONENT = "workjet-provider-gateway-host";
export const PROVIDER_GATEWAY_HOST_EXECUTABLE_ENV = "WORKJET_PROVIDER_GATEWAY_HOST_EXECUTABLE";
/** Packaged builds unpack the pinned artifact into this extra-resource directory. */
export const PROVIDER_GATEWAY_HOST_RESOURCE_DIRECTORY = "provider-gateway-host";
/** Development installs land under `<rootDir>/.deps/<this>/<version>/`. */
export const PROVIDER_GATEWAY_HOST_DEPENDENCY_DIRECTORY = "workjet-provider-gateway-host";
export const PROVIDER_GATEWAY_HOST_WORKSPACE_DIRECTORY = NodePath.join(
  "native",
  "provider-gateway-workjet-host",
  "target",
  "release",
);
export const PROVIDER_GATEWAY_HOST_MAX_EXECUTABLE_BYTES = 128 * 1024 * 1024;

const PinnedArtifact = Schema.Struct({
  triple: Schema.String,
  os: Schema.Literals(["darwin", "linux", "win32"]),
  arch: Schema.Literals(["arm64", "x64"]),
  fileName: Schema.String,
  url: Schema.String,
  byteLength: Schema.Int,
  sha256: Schema.String.pipe(Schema.check(Schema.isPattern(/^[0-9a-f]{64}$/u))),
});

const PinnedRelease = Schema.Struct({
  version: Schema.String,
  releaseTag: Schema.String,
  sourceCommit: Schema.String.pipe(Schema.check(Schema.isPattern(/^[0-9a-f]{40}$/u))),
  manifestFileName: Schema.String,
  manifestUrl: Schema.String,
  manifestByteLength: Schema.Int,
  manifestSha256: Schema.String.pipe(Schema.check(Schema.isPattern(/^[0-9a-f]{64}$/u))),
  artifacts: Schema.Array(PinnedArtifact),
});

const ProviderGatewayHostPin = Schema.Union([
  Schema.Struct({
    schema: Schema.Literal(PROVIDER_GATEWAY_HOST_PIN_SCHEMA),
    component: Schema.Literal(PROVIDER_GATEWAY_HOST_COMPONENT),
    status: Schema.Literal("unreleased"),
    unreleasedReason: Schema.String,
  }),
  Schema.Struct({
    schema: Schema.Literal(PROVIDER_GATEWAY_HOST_PIN_SCHEMA),
    component: Schema.Literal(PROVIDER_GATEWAY_HOST_COMPONENT),
    status: Schema.Literal("pinned"),
    release: PinnedRelease,
  }),
]);

export type ProviderGatewayHostPin = typeof ProviderGatewayHostPin.Type;
export type ProviderGatewayHostPinnedArtifact = typeof PinnedArtifact.Type;

export const decodeProviderGatewayHostPin = Schema.decodeUnknownSync(ProviderGatewayHostPin, {
  onExcessProperty: "error",
});

/** The pin checked into this repository. */
export const PROVIDER_GATEWAY_HOST_PIN: ProviderGatewayHostPin =
  decodeProviderGatewayHostPin(hostReleasePin);

export class ProviderGatewayHostArtifactError extends Schema.TaggedErrorClass<ProviderGatewayHostArtifactError>()(
  "ProviderGatewayHostArtifactError",
  { reason: Schema.String },
) {
  override get message(): string {
    return `The pinned Workjet provider-gateway host is unavailable: ${this.reason}`;
  }
}

export type ProviderGatewayHostSource =
  | {
      readonly _tag: "pinned";
      readonly executablePath: string;
      readonly triple: string;
      readonly version: string;
      readonly byteLength: number;
      readonly sha256: string;
    }
  | {
      readonly _tag: "override";
      readonly executablePath: string;
    }
  | {
      readonly _tag: "localBuild";
      /** Why the pinned artifact was not used; always a development-only path. */
      readonly reason: string;
    };

export interface ProviderGatewayHostHost {
  readonly platform: string;
  readonly arch: string;
}

/** Exactly the desktop environment fields this resolver reads, so it cannot drift. */
export type ProviderGatewayHostEnvironment = Pick<
  DesktopEnvironment.DesktopEnvironment["Service"],
  "isPackaged" | "resourcesPath" | "rootDir"
>;

/**
 * Where a pinned artifact for `version` lives. Packaged builds read the
 * extra-resource directory; development reads the same `.deps/` tree the
 * CTOX Business OS shell uses, keyed by version so two pins can coexist.
 */
export function resolveProviderGatewayHostRoot(
  environment: ProviderGatewayHostEnvironment,
  version: string,
): string {
  return environment.isPackaged
    ? NodePath.join(environment.resourcesPath, PROVIDER_GATEWAY_HOST_RESOURCE_DIRECTORY)
    : NodePath.join(
        environment.rootDir,
        ".deps",
        PROVIDER_GATEWAY_HOST_DEPENDENCY_DIRECTORY,
        version,
      );
}

export function findPinnedArtifactForHost(
  pin: ProviderGatewayHostPin,
  host: ProviderGatewayHostHost,
): ProviderGatewayHostPinnedArtifact | undefined {
  if (pin.status !== "pinned") return undefined;
  return pin.release.artifacts.find(
    (artifact) => artifact.os === host.platform && artifact.arch === host.arch,
  );
}

/**
 * The pure source decision. Filesystem state is checked separately so this can
 * be reasoned about (and tested) without a disk.
 */
export function decideProviderGatewayHostSource(input: {
  readonly pin: ProviderGatewayHostPin;
  readonly environment: ProviderGatewayHostEnvironment;
  readonly host: ProviderGatewayHostHost;
  readonly executableOverride?: string | undefined;
}): ProviderGatewayHostSource {
  const override = input.executableOverride?.trim();
  if (override !== undefined && override.length > 0) {
    return { _tag: "override", executablePath: override };
  }
  if (input.pin.status === "unreleased") {
    return { _tag: "localBuild", reason: input.pin.unreleasedReason };
  }
  const artifact = findPinnedArtifactForHost(input.pin, input.host);
  if (artifact === undefined) {
    return {
      _tag: "localBuild",
      reason: `The pinned release ${input.pin.release.releaseTag} publishes no artifact for ${input.host.platform}-${input.host.arch}.`,
    };
  }
  return {
    _tag: "pinned",
    executablePath: NodePath.join(
      resolveProviderGatewayHostRoot(input.environment, input.pin.release.version),
      artifact.fileName,
    ),
    triple: artifact.triple,
    version: input.pin.release.version,
    byteLength: artifact.byteLength,
    sha256: artifact.sha256,
  };
}

/**
 * Prove the on-disk executable is exactly the pinned bytes. Returns the failure
 * reason instead of throwing so callers can decide between hard failure
 * (packaged) and fallback (development).
 */
export function verifyPinnedExecutable(input: {
  readonly executablePath: string;
  readonly byteLength: number;
  readonly sha256: string;
}): string | undefined {
  let stat: NodeFS.Stats;
  try {
    stat = NodeFS.lstatSync(input.executablePath);
  } catch {
    return `${input.executablePath} does not exist.`;
  }
  if (stat.isSymbolicLink() || !stat.isFile()) {
    return `${input.executablePath} is not a regular file.`;
  }
  if (stat.size !== input.byteLength) {
    return `${input.executablePath} is ${stat.size} bytes; the pin records ${input.byteLength}.`;
  }
  if (stat.size > PROVIDER_GATEWAY_HOST_MAX_EXECUTABLE_BYTES) {
    return `${input.executablePath} exceeds the executable byte budget.`;
  }
  let digest: string;
  try {
    digest = NodeCrypto.createHash("sha256")
      .update(NodeFS.readFileSync(input.executablePath))
      .digest("hex");
  } catch {
    return `${input.executablePath} could not be read for digest verification.`;
  }
  if (digest !== input.sha256) {
    return `${input.executablePath} has SHA-256 ${digest}; the pin records ${input.sha256}.`;
  }
  return undefined;
}

export interface ResolvedProviderGatewayHost {
  /**
   * The executable the desktop should force via
   * `WORKJET_PROVIDER_GATEWAY_HOST_EXECUTABLE`, or `undefined` to leave the
   * server's existing default resolution (the development local-build path) in
   * place.
   */
  readonly executablePath: string | undefined;
  readonly source: "pinned" | "override" | "workspace-build" | "local-build";
  /** Present for `local-build`: why the pinned artifact was not used. */
  readonly reason?: string;
  readonly version?: string;
  readonly triple?: string;
}

export function resolveWorkspaceProviderGatewayHostExecutable(input: {
  readonly environment: ProviderGatewayHostEnvironment;
  readonly host: ProviderGatewayHostHost;
}): string | undefined {
  if (input.environment.isPackaged) return undefined;
  const executablePath = NodePath.join(
    input.environment.rootDir,
    PROVIDER_GATEWAY_HOST_WORKSPACE_DIRECTORY,
    input.host.platform === "win32"
      ? `${PROVIDER_GATEWAY_HOST_COMPONENT}.exe`
      : PROVIDER_GATEWAY_HOST_COMPONENT,
  );
  try {
    const stat = NodeFS.lstatSync(executablePath);
    if (
      stat.isSymbolicLink() ||
      !stat.isFile() ||
      stat.size <= 0 ||
      stat.size > PROVIDER_GATEWAY_HOST_MAX_EXECUTABLE_BYTES
    ) {
      return undefined;
    }
    return executablePath;
  } catch {
    return undefined;
  }
}

/**
 * Resolve the host executable, verifying the pin's digest when one applies.
 * Fails only for a packaged build whose pin cannot be satisfied.
 */
export function resolveProviderGatewayHostExecutable(input: {
  readonly pin?: ProviderGatewayHostPin;
  readonly environment: ProviderGatewayHostEnvironment;
  readonly host: ProviderGatewayHostHost;
  readonly executableOverride?: string | undefined;
  readonly verify?: (input: {
    readonly executablePath: string;
    readonly byteLength: number;
    readonly sha256: string;
  }) => string | undefined;
  readonly resolveWorkspaceBuild?: (input: {
    readonly environment: ProviderGatewayHostEnvironment;
    readonly host: ProviderGatewayHostHost;
  }) => string | undefined;
}): Effect.Effect<ResolvedProviderGatewayHost, ProviderGatewayHostArtifactError> {
  return Effect.suspend(() => {
    const pin = input.pin ?? PROVIDER_GATEWAY_HOST_PIN;
    const verify = input.verify ?? verifyPinnedExecutable;
    const decided = decideProviderGatewayHostSource({
      pin,
      environment: input.environment,
      host: input.host,
      executableOverride: input.executableOverride,
    });

    if (decided._tag === "override") {
      return Effect.succeed<ResolvedProviderGatewayHost>({
        executablePath: decided.executablePath,
        source: "override",
      });
    }

    const unmetReason =
      decided._tag === "pinned"
        ? verify({
            executablePath: decided.executablePath,
            byteLength: decided.byteLength,
            sha256: decided.sha256,
          })
        : decided.reason;

    if (decided._tag === "pinned" && unmetReason === undefined) {
      return Effect.succeed<ResolvedProviderGatewayHost>({
        executablePath: decided.executablePath,
        source: "pinned",
        version: decided.version,
        triple: decided.triple,
      });
    }

    const workspaceExecutable = input.environment.isPackaged
      ? undefined
      : (input.resolveWorkspaceBuild ?? resolveWorkspaceProviderGatewayHostExecutable)({
          environment: input.environment,
          host: input.host,
        });
    if (workspaceExecutable !== undefined) {
      return Effect.succeed<ResolvedProviderGatewayHost>({
        executablePath: workspaceExecutable,
        source: "workspace-build",
        ...(unmetReason === undefined ? {} : { reason: unmetReason }),
      });
    }

    const reason = unmetReason ?? "The provider-gateway host pin could not be resolved.";
    if (input.environment.isPackaged) {
      return Effect.fail(new ProviderGatewayHostArtifactError({ reason }));
    }
    return Effect.succeed<ResolvedProviderGatewayHost>({
      executablePath: undefined,
      source: "local-build",
      reason,
    });
  });
}
