//! CTOX-owned web stack.
//!
//! This crate exists as an explicit compile and ownership boundary for the
//! browser/search/read surface so the root `ctox` binary only carries thin
//! adapters for those capabilities.

pub mod browser;
#[cfg(feature = "full")]
pub mod capability;
#[cfg(feature = "full")]
pub mod deep_research;
#[cfg(feature = "full")]
pub(crate) mod egress;
#[cfg(feature = "full")]
pub mod person_ranking;
#[cfg(feature = "full")]
pub mod person_research;
pub mod runtime_config;
#[cfg(feature = "full")]
pub mod scholarly_search;
#[cfg(feature = "full")]
pub mod sources;
#[cfg(feature = "full")]
pub mod surface;
#[cfg(feature = "full")]
pub mod unlock;
#[cfg(feature = "full")]
pub mod unlock_report;
#[cfg(feature = "full")]
pub mod web_search;

pub use browser::browser_doctor_report;
pub use browser::browser_doctor_report_with_context;
pub use browser::capture_browser_transport;
pub use browser::capture_browser_transport_with_context;
pub use browser::handle_browser_command;
pub use browser::handle_browser_command_with_context;
pub use browser::prepare_browser_environment;
pub use browser::prepare_browser_environment_with_context;
pub use browser::run_browser_automation;
pub use browser::run_browser_automation_with_context;
pub use browser::spawn_persistent_browser;
pub use browser::spawn_persistent_browser_with_context;
pub use browser::BrowserAutomationRequest;
pub use browser::BrowserCaptureRequest;
pub use browser::BrowserPrepareOptions;
pub use browser::PersistentBrowserHandle;
pub use browser::PersistentBrowserSpawn;
#[cfg(feature = "full")]
pub use capability::execute_web_stack_capability;
#[cfg(feature = "full")]
pub use capability::web_stack_capability_contracts;
#[cfg(feature = "full")]
pub use capability::WebStackCapabilityContract;
#[cfg(feature = "full")]
pub use capability::WebStackCapabilityError;
#[cfg(feature = "full")]
pub use capability::WebStackCapabilityErrorKind;
#[cfg(feature = "full")]
pub use capability::WebStackCapabilityLimits;
#[cfg(feature = "full")]
pub use capability::WebStackCapabilityTool;
#[cfg(feature = "full")]
pub use capability::WEB_STACK_CAPABILITY_ADAPTER_FIXTURE_V1_JSON;
#[cfg(feature = "full")]
pub use deep_research::run_ctox_deep_research_tool;
#[cfg(feature = "full")]
pub use deep_research::run_deep_research_tool_with_context;
#[cfg(feature = "full")]
pub use deep_research::DeepResearchDepth;
#[cfg(feature = "full")]
pub use deep_research::DeepResearchRequest;
#[cfg(feature = "full")]
pub use egress::allow_hosts_from_config as browser_egress_allow_hosts_from_config;
#[cfg(feature = "full")]
pub use egress::allow_hosts_from_context as browser_egress_allow_hosts_from_context;
#[cfg(feature = "full")]
pub use egress::assert_browser_egress_url;
#[cfg(feature = "full")]
pub use egress::assert_browser_egress_url_with_context;
#[cfg(feature = "full")]
pub use person_research::merge_person_research_source_records;
#[cfg(feature = "full")]
pub use person_research::persist_person_research_workspace;
#[cfg(feature = "full")]
pub use person_research::run_ctox_person_research_tool;
#[cfg(feature = "full")]
pub use person_research::run_person_research_tool_with_context;
pub use person_research::KnownPersonRecord;
#[cfg(feature = "full")]
pub use person_research::PersonResearchRequest;
#[cfg(feature = "full")]
pub use scholarly_search::execute_scholarly_search;
#[cfg(feature = "full")]
pub use scholarly_search::execute_scholarly_search_with_context;
#[cfg(feature = "full")]
pub use scholarly_search::run_ctox_scholarly_search_tool;
#[cfg(feature = "full")]
pub use scholarly_search::run_scholarly_search_tool_with_context;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlyResult;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchProvider;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchRequest;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchResponse;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_CONTENT_TYPES;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_DEFAULT_BASE_URL;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_SORT_VALUES;
#[cfg(feature = "full")]
pub use scholarly_search::UNPAYWALL_DEFAULT_BASE_URL;
#[cfg(feature = "full")]
pub use surface::handle_web_command;
#[cfg(feature = "full")]
pub use surface::handle_web_command_with_context;
#[cfg(feature = "full")]
pub use surface::WebScrapeRequest;
#[cfg(feature = "full")]
pub use unlock::handle_unlock_command;
#[cfg(feature = "full")]
pub use unlock::handle_unlock_command_with_context;
#[cfg(feature = "full")]
pub use unlock_report::generate_acceptance_report;
#[cfg(feature = "full")]
pub use unlock_report::handle_report_command;
#[cfg(feature = "full")]
pub use web_search::augment_responses_request;
#[cfg(feature = "full")]
pub use web_search::augment_responses_request_with_context;
#[cfg(feature = "full")]
pub use web_search::execute_canonical_web_search;
#[cfg(feature = "full")]
pub use web_search::execute_canonical_web_search_with_context;
#[cfg(feature = "full")]
pub use web_search::run_ctox_web_read_tool;
#[cfg(feature = "full")]
pub use web_search::run_ctox_web_search_tool;
#[cfg(feature = "full")]
pub use web_search::run_web_read_tool_with_context;
#[cfg(feature = "full")]
pub use web_search::run_web_search_tool_with_context;
#[cfg(feature = "full")]
pub use web_search::CanonicalWebSearchExecution;
#[cfg(feature = "full")]
pub use web_search::CanonicalWebSearchRequest;
#[cfg(feature = "full")]
pub use web_search::ContextSize;
#[cfg(feature = "full")]
pub use web_search::DirectWebReadRequest;
#[cfg(feature = "full")]
pub use web_search::OpenAiWebSearchCompatMode;
#[cfg(feature = "full")]
pub use web_search::SearchUserLocation;

pub use runtime_config::CtoxRuntimeConfigStore;
pub use runtime_config::RuntimeConfigStore;
pub use runtime_config::WebStackContext;
pub use runtime_config::WorkjetRuntimeConfigStore;
