//! CTOX-owned web stack.
//!
//! This crate exists as an explicit compile and ownership boundary for the
//! browser/search/read surface so the root `ctox` binary only carries thin
//! adapters for those capabilities.

pub mod browser;
#[cfg(feature = "full")]
pub mod deep_research;
#[cfg(feature = "full")]
pub(crate) mod egress;
#[cfg(feature = "full")]
pub mod person_research;
pub(crate) mod runtime_config;
#[cfg(feature = "full")]
pub mod scholarly_search;
#[cfg(feature = "full")]
pub mod sources;
#[cfg(feature = "full")]
pub mod surface;
#[cfg(feature = "full")]
pub mod unlock;
#[cfg(feature = "full")]
pub mod web_search;

pub use browser::browser_doctor_report;
pub use browser::capture_browser_transport;
pub use browser::handle_browser_command;
pub use browser::prepare_browser_environment;
pub use browser::run_browser_automation;
pub use browser::spawn_persistent_browser;
pub use browser::BrowserAutomationRequest;
pub use browser::BrowserCaptureRequest;
pub use browser::BrowserPrepareOptions;
pub use browser::PersistentBrowserHandle;
pub use browser::PersistentBrowserSpawn;
#[cfg(feature = "full")]
pub use deep_research::run_ctox_deep_research_tool;
#[cfg(feature = "full")]
pub use deep_research::DeepResearchDepth;
#[cfg(feature = "full")]
pub use deep_research::DeepResearchRequest;
#[cfg(feature = "full")]
pub use egress::allow_hosts_from_config as browser_egress_allow_hosts_from_config;
#[cfg(feature = "full")]
pub use egress::assert_browser_egress_url;
#[cfg(feature = "full")]
pub use person_research::run_ctox_person_research_tool;
#[cfg(feature = "full")]
pub use person_research::PersonResearchRequest;
#[cfg(feature = "full")]
pub use scholarly_search::execute_scholarly_search;
#[cfg(feature = "full")]
pub use scholarly_search::run_ctox_scholarly_search_tool;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlyResult;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchProvider;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchRequest;
#[cfg(feature = "full")]
pub use scholarly_search::ScholarlySearchResponse;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_CONTENT_TYPES;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_DEFAULT_BASE_URL;
#[cfg(feature = "full")]
pub use scholarly_search::ANNAS_ARCHIVE_SORT_VALUES;
#[cfg(feature = "full")]
pub use scholarly_search::UNPAYWALL_DEFAULT_BASE_URL;
#[cfg(feature = "full")]
pub use surface::handle_web_command;
#[cfg(feature = "full")]
pub use surface::WebScrapeRequest;
#[cfg(feature = "full")]
pub use unlock::handle_unlock_command;
#[cfg(feature = "full")]
pub use web_search::augment_responses_request;
#[cfg(feature = "full")]
pub use web_search::execute_canonical_web_search;
#[cfg(feature = "full")]
pub use web_search::run_ctox_web_read_tool;
#[cfg(feature = "full")]
pub use web_search::run_ctox_web_search_tool;
#[cfg(feature = "full")]
pub use web_search::CanonicalWebSearchExecution;
#[cfg(feature = "full")]
pub use web_search::CanonicalWebSearchRequest;
#[cfg(feature = "full")]
pub use web_search::ContextSize;
#[cfg(feature = "full")]
pub use web_search::DirectWebReadRequest;
#[cfg(feature = "full")]
pub use web_search::OpenAiWebSearchCompatMode;
#[cfg(feature = "full")]
pub use web_search::SearchUserLocation;
